swagger: '2.0'
info:
  version: '1.0'
  title: "iFarm"
  description: 农场管理接口信息
    
host: polls.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /mating:
    x-summary: 配种信息
    post:
      summary: 新增配种
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Mating'
      responses:
        '200':
          description: 保存成功
  /brith:
    x-summary: 分娩信息
    post: 
      summary: 新增分娩
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Brith'
      responses:
        200: 
          description: 保存成功
definitions:
  Mating:
    properties:
      date:
        type: string
        description: 配种日期
      executor-id:
        type: number
        description: 技术员
      swine-id:
        type: string
        description: 母猪ID
      swine-lead-id:
        type: string
        description: 主公猪
      boars:
        type: array
        description: 公猪信息
        items:
          type: object
          properties:
            mating-mode:
              type: number
              description: 配种方式
            swine-id:
              type: string
              description: 公猪耳号
            time:
              type: number
              description: 配种次数
    required:
      - date
      - executor-id
  Brith:
    properties:
      date: 
        type: string
        description: 日期
      swine-id: 
        type: string
        description: 母猪耳号
      brith-pig: 
        type: number
        description: 出生
      health-pig:
        type: number
        description: 健仔
      dead-pig:
        type: number
        description: 死亡
      deformity-pig:
        type: number
        description: 畸形
      mummy-pig:
        type: number
        description: 木乃伊
      weak-pig:
        type: number
        description: 弱仔
      crush-pig:
        type: number
        description: 压死
      swine-num: 
        type: number
        description: 母猪数量
      boar-num:
        type: number
        description: 公猪数量
      total-weight: 
        type: number
        description: 总重
      average-weight: 
        type: number
        description: 均重
      varieties: 
        type: number
        description: 品种
      boar-mode:
        type: number
        description: 公猪耳号（奇数，偶数）
      boar-start:
        type: number
        description: 开始号码
      boar-over:
        type: number
        description: 结束号码
      boar-weight:
        type: number
        description: 公猪窝重量
      swine-mode:
        type: number
        description: 母猪耳号（奇数，偶数）
      swine-start:
        type: number
        description: 开始号码
      swine-over:
        type: number
        description: 结束号码
      swine-weight:
        type: number
        description: 母猪窝重量