swagger: '2.0'
info:
  version: '1.0'
  title: "iFarm"
  description: ifrarm接口
    
host: polls.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /mating:
    x-summary: 配种信息
    get:
      summary: 每日任务列表
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/Req-task'
            
      responses:
        200:
          description: "成功返回数据"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Res-task"
definitions:
  Req-task:
    properties:
      date:
        type: string
        description: 任务时间戳
    required:
      - date
  Res-task:
    properties:
      name: 
        type: string  
        description: 动作名称
      type: 
        type: string
        description: 动作所对应的类型, 用于用户设置跳转的路径. 0配种, 1分娩, 2断奶
      swine-id: 
        type: string
        description: 母猪耳号
      location:
        type: string
        description: 猪所在栏舍
      status:
        type: number
        description: 任务状态, 0正常, 1延迟、